<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="2025" started-at="2019-01-02T03:09:54Z" finished-at="2019-01-02T03:09:56Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="2025" started-at="2019-01-02T03:09:54Z" finished-at="2019-01-02T03:09:56Z">
      <class name="day201902.time">
        <test-method status="FAIL" signature="add()[pri:0, instance:day201902.time@2d6a9952]" name="add" duration-ms="2014" started-at="2019-01-02T11:09:54Z" finished-at="2019-01-02T11:09:56Z">
          <exception class="org.testng.internal.thread.ThreadTimeoutException">
            <message>
              <![CDATA[Method org.testng.internal.TestNGMethod.add() didn't finish within the time-out 2000]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.add() didn't finish within the time-out 2000
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.thread.ThreadTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- add -->
      </class> <!-- day201902.time -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
